# Generated by Django 5.1 on 2024-09-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_contact', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('origin_location', models.CharField(max_length=200)),
                ('end_location', models.CharField(max_length=200)),
                ('last_maintenance', models.DateField()),
                ('next_maintenance', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('on_time', models.BooleanField(null=True)),
            ],
        ),
    ]
